# Generated by Django 4.2.2 on 2023-06-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0007_mbkkdetail_dtlocdistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbkkaround',
            name='mb_plat',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mbkkaround',
            name='mb_plng',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
